#PROG=	sample1
PROG_CXX=	sample1
MAN=
LDADD=	-lspblas

#SRCS=	sample1.c
SRCS=	sample1.cc

WARNS=	3
#CFLAGS+=	-I/usr/local/include
CXXFLAGS+=	-I/usr/local/include
LDFLAGS+=	-L/usr/local/lib

.include <bsd.prog.mk>
