PROGS=	vec list hash hash-str

MAN.vec=
LDADD.vec=
SRCS.vec=	vec.c
CFLAGS.vec+=	-I/usr/local/include/klib
WARNS.vec=	3

MAN.list=
LDADD.list=
SRCS.list=	list.c
CFLAGS.list+=	-I/usr/local/include/klib
WARNS.list=	3

MAN.hash=
LDADD.hash=
SRCS.hash=	hash.c
CFLAGS.hash+=	-I/usr/local/include/klib
WARNS.hash=	3

MAN.hash-str=
LDADD.hash-str=
SRCS.hash-str=	hash-str.c
CFLAGS.hash-str+=	-I/usr/local/include/klib
WARNS.hash-str=	3

.include <bsd.progs.mk>
