PROGS=	sample err-in-constructor

MAN.sample=
LDADD.sample=
SRCS.sample=	sample.c
WARNS.sample=	3

MAN.err-in-constructor=
LDADD.err-in-constructor=
SRCS.err-in-constructor=	err-in-constructor.c
WARNS.err-in-constructor=	3

.include <bsd.progs.mk>
