PROGS=	string list hash array

MAN.string=
LDADD.string=
SRCS.string=	string.c
CFLAGS.string+=	-I/usr/local/include
WARNS.string=	3

MAN.list=
LDADD.list=
SRCS.list=	list.c
CFLAGS.list+=	-I/usr/local/include
WARNS.list=	3

MAN.hash=
LDADD.hash=
SRCS.hash=	hash.c
CFLAGS.hash+=	-I/usr/local/include
WARNS.hash=	3

MAN.array=
LDADD.array=
SRCS.array=	array.c
CFLAGS.array+=	-I/usr/local/include
WARNS.array=	3

.include <bsd.progs.mk>
